### ISSUE TITLE
puTTY를 원격으로 전송하고 싶습니다.

### ISSUE THREAD

**Issue by JimJeon** [CNU-Developers/CNUServiceAndUpdator#11]
cnu updator를 이용하여 puTTY.exe 파일을 원격으로 전송하고 싶습니다.

**Comment by JimJeon** [comment]
"chrome https://the.earth.li/~sgtatham/putty/latest/x86/putty.exe"
를 이용해서 해결했습니다.

하지만 역시나 windows 10이 실행이 안되더군요...
저번에 분명 net user...를 실행시켰던거 같은데 새로운 windows 10의 등장인지
아니면 net user....가 reboot 후에 죽는건지 잘 모르겠습니다.
사실 net user.... 뭐 하는 친구인지도 모르겠습니다... ㅠ

**Comment by minhoryang** [comment]
@JimJeon 윈10에서는 #10 의 문제를 해결해야 될 것 같습니다.
새로운 윈10의 등장 때문이겠지요.

시스템 설정을 바꿔주는거라 reboot과는 상관이 없습니다.
`net user administrator password /active:yes *`
는 administrator라는 계정을 password라는 암호를 통해서 사용할 수 있도록 (active) 해달라는 명령입니다.
